{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ff0bed52",
   "metadata": {},
   "outputs": [],
   "source": [
    "from flask import Flask, request, render_template, jsonify\n",
    "from werkzeug.utils import secure_filename\n",
    "import os\n",
    "import PyPDF2\n",
    "from docx import Document\n",
    "from sklearn.feature_extraction.text import TfidfVectorizer\n",
    "from sklearn.metrics.pairwise import cosine_similarity\n",
    "\n",
    "app = Flask(__name__)\n",
    "\n",
    "# Configuration for file uploads\n",
    "app.config['UPLOAD_FOLDER'] = 'uploads'\n",
    "app.config['ALLOWED_EXTENSIONS'] = {'pdf', 'docx', 'txt'}\n",
    "\n",
    "def allowed_file(filename):\n",
    "    return '.' in filename and filename.rsplit('.', 1)[1].lower() in app.config['ALLOWED_EXTENSIONS']\n",
    "\n",
    "def extract_text_from_pdf(pdf_path):\n",
    "    with open(pdf_path, 'rb') as file:\n",
    "        reader = PyPDF2.PdfFileReader(file)\n",
    "        text = \"\"\n",
    "        for page in range(reader.numPages):\n",
    "            text += reader.getPage(page).extractText()\n",
    "    return text\n",
    "\n",
    "def extract_text_from_docx(docx_path):\n",
    "    doc = Document(docx_path)\n",
    "    text = \"\"\n",
    "    for para in doc.paragraphs:\n",
    "        text += para.text\n",
    "    return text\n",
    "\n",
    "def extract_text_from_txt(txt_path):\n",
    "    with open(txt_path, 'r') as file:\n",
    "        text = file.read()\n",
    "    return text\n",
    "\n",
    "def match_job(resume_text, job_descriptions):\n",
    "    # TF-IDF Vectorization\n",
    "    tfidf_vectorizer = TfidfVectorizer(stop_words='english')\n",
    "    all_text = [resume_text] + job_descriptions\n",
    "    tfidf_matrix = tfidf_vectorizer.fit_transform(all_text)\n",
    "\n",
    "    # Calculate Cosine Similarity between the resume and all job descriptions\n",
    "    cosine_sim = cosine_similarity(tfidf_matrix[0:1], tfidf_matrix[1:])\n",
    "    return cosine_sim[0]\n",
    "\n",
    "@app.route('/')\n",
    "def index():\n",
    "    return render_template('index.html')\n",
    "\n",
    "@app.route('/upload', methods=['POST'])\n",
    "def upload_file():\n",
    "    if 'resume' not in request.files:\n",
    "        return 'No file part'\n",
    "    file = request.files['resume']\n",
    "    if file.filename == '':\n",
    "        return 'No selected file'\n",
    "    if file and allowed_file(file.filename):\n",
    "        filename = secure_filename(file.filename)\n",
    "        filepath = os.path.join(app.config['UPLOAD_FOLDER'], filename)\n",
    "        file.save(filepath)\n",
    "\n",
    "        # Extract text from the uploaded resume\n",
    "        if filename.endswith('.pdf'):\n",
    "            resume_text = extract_text_from_pdf(filepath)\n",
    "        elif filename.endswith('.docx'):\n",
    "            resume_text = extract_text_from_docx(filepath)\n",
    "        elif filename.endswith('.txt'):\n",
    "            resume_text = extract_text_from_txt(filepath)\n",
    "\n",
    "        # Sample job descriptions (In a real app, this could come from a database or API)\n",
    "        job_descriptions = [\n",
    "            \"Data Scientist with experience in Python, Machine Learning, and Data Analysis.\",\n",
    "            \"Software Engineer proficient in Java and Python, with experience in full-stack development.\",\n",
    "            \"AI Researcher with a focus on deep learning and computer vision.\",\n",
    "        ]\n",
    "\n",
    "        # Match the resume to the job descriptions\n",
    "        similarity_scores = match_job(resume_text, job_descriptions)\n",
    "\n",
    "        # Find the best match\n",
    "        best_match_idx = similarity_scores.argmax()\n",
    "        best_match = job_descriptions[best_match_idx]\n",
    "        best_score = similarity_scores[best_match_idx]\n",
    "\n",
    "        return render_template('result.html', best_match=best_match, best_score=best_score)\n",
    "\n",
    "    return 'Invalid file format'\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    app.run(debug=True, host='0.0.0.0', port=3000)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
